<?php
$session = new Session();
$user_controller = new UserController();

$permamount = 1;

if($session->exists('username')) {
    $user = $user_controller->getByUsername( $_SESSION[ 'username' ] );
    $permamount = $user->getGebruikerRechtgroep();
}
else {
}

/*
define('CAN_SHOW_PSOVERVIEW',   1);
define('CAN_SHOW_PROGRESS',      2);
define('CAN_SHOW_PASSFORGET',   4);
define('CAN_SHOW_PASSRESTORE',   8);
define('CAN_EDIT_PASSWORD',    16);
define('CAN_SHOW_USER',           32);
define('CAN_SHOW_CURSUS',         64);
define('CAN_SHOW_LOCATION',       128);
define('CAN_SHOW_EDUCATION',      256);
define('CAN_SHOW_EDUCATIONBLOCK', 512);
define('CAN_EDIT_LOCATION',       1024);
define('CAN_SHOW_STUDENTOVERVIEW', 2048);
define('CAN_CREATE_PROGRESS',     4096);
define('CAN_EDIT_PROGRESS',       8192);
define('CAN_CREATE_CURSUS',       16384);
define('CAN_EDIT_CURSUS',       32768);
define('CAN_CREATE_CURSUSBLOCK',  65536);
define('CAN_CREATE_USER',       131072);
define('CAN_CREATE_LOCATION',    262144);
define('CAN_CREATE_EDUCATION',   524288);
define('CAN_CREATE_EDUCATIONBLOCK',1048576);
define('CAN_EDIT_EDUCATIONBLOCK',2097152);
define('CAN_EDIT_EDUCATION',    4194304);
define('CAN_EDIT_USER',         8388608);

$user1 = new Permission();
$user1 = [];

if($permamount == "1"){ $user1['permission'] = CAN_SHOW_PSOVERVIEW + CAN_SHOW_PROGRESS + CAN_SHOW_PASSFORGET + CAN_SHOW_PASSRESTORE + CAN_EDIT_PASSWORD + CAN_SHOW_USER + CAN_SHOW_CURSUS + CAN_SHOW_LOCATION +
    CAN_SHOW_EDUCATION + CAN_SHOW_EDUCATIONBLOCK + CAN_EDIT_LOCATION;}

if($permamount == "2"){ $user1['permission'] = CAN_SHOW_PSOVERVIEW + CAN_SHOW_PROGRESS + CAN_SHOW_PASSFORGET + CAN_SHOW_PASSRESTORE + CAN_EDIT_PASSWORD + CAN_SHOW_USER + CAN_SHOW_CURSUS + CAN_SHOW_LOCATION +
    CAN_SHOW_EDUCATION + CAN_SHOW_EDUCATIONBLOCK + CAN_EDIT_LOCATION + CAN_SHOW_STUDENTOVERVIEW + CAN_CREATE_PROGRESS +CAN_EDIT_PROGRESS + CAN_CREATE_CURSUS + CAN_EDIT_CURSUS +
    CAN_CREATE_CURSUSBLOCK + CAN_CREATE_USER + CAN_CREATE_LOCATION + CAN_CREATE_EDUCATION + CAN_CREATE_EDUCATIONBLOCK + CAN_EDIT_EDUCATIONBLOCK + CAN_EDIT_EDUCATION + CAN_EDIT_USER;}

if($permamount =="2" ){ $user1 = array(CAN_SHOW_PSOVERVIEW, CAN_SHOW_PROGRESS); }
*/

if($permamount =="2" ){ $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD', 'CAN_SHOW_STUDENTOVERVIEW', 'CAN_SHOW_PROGRESS', 'CAN_EDIT_PROGRESS','CAN_SHOW_PROGRESS', 'CAN_CREATE_PROGRESS', 'CAN_EDIT_PROGRESS'); }

else if($permamount =="3" ){ $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD', 'CAN_SHOW_STUDENTOVERVIEW', 'CAN_SHOW_PROGRESS','CAN_SHOW_PROGRESS', 'CAN_CREATE_PROGRESS', 'CAN_EDIT_PROGRESS'); }

else if($permamount =="4" ){ $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD', 'CAN_SHOW_STUDENTOVERVIEW', 'CAN_SHOW_PROGRESS', 'CAN_EDIT_PROGRESS','CAN_SHOW_PROGRESS', 'CAN_CREATE_PROGRESS', 'CAN_EDIT_PROGRESS'); }

else if($permamount =="5" ){ $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD', 'CAN_SHOW_USER', 'CAN_SHOW_CURSUS', 'CAN_SHOW_LOCATION',
    'CAN_SHOW_EDUCATION', 'CAN_SHOW_EDUCATIONBLOCK', 'CAN_EDIT_LOCATION', 'CAN_SHOW_STUDENTOVERVIEW', 'CAN_SHOW_PROGRESS', 'CAN_CREATE_PROGRESS', 'CAN_EDIT_PROGRESS', 'CAN_CREATE_CURSUS', 'CAN_EDIT_CURSUS', 'CAN_CREATE_CURSUSBLOCK', 'CAN_CREATE_USER', 'CAN_CREATE_LOCATION', 'CAN_CREATE_EDUCATION', 'CAN_CREATE_EDUCATIONBLOCK', 'CAN_EDIT_EDUCATIONBLOCK', 'CAN_EDIT_EDUCATION', 'CAN_EDIT_USER', 'CAN_CONNECT_EDUCATION'); }

else {
    $user1 = array('CAN_SHOW_PSOVERVIEW', 'CAN_EDIT_PASSWORD');
}
/*
$foo =  8;
$bar = 8;
*/
//var_dump($user->allowed(6 , CAN_SHOW_PROGRESS));
?>
